name: Bug Report
description: Report a problem with the ecks RPG Framework
title: "[Bug] "
labels:
  - bug
body:

  - type: input
    id: version
    attributes:
      label: Engine Version
      description: What version of ecks are you using?
      placeholder: v0.52.196
    validations:
      required: true

  - type: checkboxes
    id: system
    attributes:
      label: Affected System
      description: Which major system is affected?
      options:
        - Core Framework
        - Addons
        - Data
        - Economy
        - Entity
        - Launch
        - Loot
        - Progression
        - UI
        - World
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: subsystem
    attributes:
      label: Affected Subsystem
      description: Which specific area is affected?
      options:
        # Addons
        - Item Creator
        - XP Analyzer

        # Data
        - Databases
        - Generators
        - Templates

        # Economy
        - Crafting
        - Currency
        - Shops
        - Trading

        # Entity
        - Behaviors
        - Characters
        - Class
        - Combat
        - Difficulty
        - Effects
        - NPC
        - Stats
        - XP

        # Launch
        - Bootloader
        - Title Screen
        - Start Menu
        - World Injector

        # Loot
        - Chests
        - Equipment
        - Inventory
        - Items

        # Progression
        - Achievements
        - Dialogue
        - Quests

        # UI
        - HUD
        - Menus
        - Runtime

        # World
        - Map Change
        - Chunks
        - Destroyables
        - Environment Audio
        - Environment Weather
        - Maps
        - Teleporter

        - Other

  - type: textarea
    id: issue
    attributes:
      label: Description
      description: Explain the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: How can this issue be reproduced?
      placeholder: |
        1. Open menu
        2. Perform action
        3. Observe issue

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs
      description: Add screenshots, errors, or logs if available.
